<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MenuSeeder extends Seeder
{
    public function run()
    {
        $menus = [
            [
                'nama'        => 'Laksa Benteng Original Ayam Suwir',
                'slug'        => 'laksa-benteng-original-ayam-suwir',
                'kategori'    => 'Laksa Klasik',
                'harga'       => 25000,
                'deskripsi'   => 'Laksa otentik khas Pasar Lama Tangerang dengan bihun tepung beras kenyal, siraman kuah santan kuning kental gurih, suwiran ayam kampung, taburan kelapa sangrai (serundeng), daun kesum aromatik, dan emping renyah.',
                'komposisi'   => 'Bihun tepung beras putih, kuah santan kaldu ayam bumbu rempah kuning, ayam kampung suwir, kelapa sangrai (serundeng manis-gurih), daun kucai/kesum, emping melinjo, tauge segar.',
                'level_pedas' => 1,
                'rating'      => 4.9,
                'is_favorite' => 1,
                'gambar'      => 'laksa-original.jpg',
                'status'      => 'tersedia',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nama'        => 'Laksa Benteng Spesial Ayam Panggang',
                'slug'        => 'laksa-benteng-spesial-ayam-panggang',
                'kategori'    => 'Laksa Spesial',
                'harga'       => 32000,
                'deskripsi'   => 'Kreasi premium dengan potongan paha ayam kampung bakar beraroma asap menggugah selera, disajikan di atas kuah santan kuning pekat kaya rempah lengkuas dan kunyit khas Banten.',
                'komposisi'   => 'Bihun beras segar, paha ayam kampung marinasi bakar kecap rempah, kuah santan kental, serundeng kelapa, emping melinjo, daun kesum, sambal cabai rawit merah.',
                'level_pedas' => 2,
                'rating'      => 4.8,
                'is_favorite' => 1,
                'gambar'      => 'laksa-ayam-panggang.jpg',
                'status'      => 'tersedia',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nama'        => 'Laksa Benteng Komplit Telur Puyuh & Ati Ampela',
                'slug'        => 'laksa-benteng-komplit-telur-puyuh-ati-ampela',
                'kategori'    => 'Laksa Komplit',
                'harga'       => 35000,
                'deskripsi'   => 'Pilihan paling disukai pecinta kuliner tradisional: laksa dengan topping tusukan telur puyuh gurih dan ati ampela ungkep bumbu kuning empuk meresap.',
                'komposisi'   => 'Bihun beras khas Benteng, kuah santan gurih berempah, 4 butir telur puyuh rebus bumbu, ati ampela ungkep empuk, serundeng kelapa sangrai, emping renyah.',
                'level_pedas' => 2,
                'rating'      => 4.9,
                'is_favorite' => 1,
                'gambar'      => 'laksa-komplit-puyuh.jpg',
                'status'      => 'tersedia',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nama'        => 'Laksa Benteng Seafood Udang Windu & Cumi',
                'slug'        => 'laksa-benteng-seafood-udang-windu-cumi',
                'kategori'    => 'Laksa Seafood',
                'harga'       => 45000,
                'deskripsi'   => 'Perpaduan cita rasa pesisir Banten dan keaslian Laksa Benteng: udang windu segar berukuran besar dan irisan cumi empuk dalam kuah kaldu laksa laut yang nikmat.',
                'komposisi'   => 'Bihun beras, udang windu segar saus mentega rempah, cumi iris lembut, kaldu udang dan santan kental, serundeng, daun kesum, jeruk limau, emping.',
                'level_pedas' => 2,
                'rating'      => 4.7,
                'is_favorite' => 0,
                'gambar'      => 'laksa-seafood.jpg',
                'status'      => 'tersedia',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nama'        => 'Laksa Benteng Daging Sapi Suwir Serundeng',
                'slug'        => 'laksa-benteng-daging-sapi-suwir-serundeng',
                'kategori'    => 'Laksa Spesial',
                'harga'       => 38000,
                'deskripsi'   => 'Variasi daging sapi sengkel pilihan yang dimasak perlahan hingga lumer dan disuwir tebal, berpadu harmonis dengan gurihnya kelapa sangrai dan kaldu santan gurih.',
                'komposisi'   => 'Bihun beras putih, daging sapi sengkel empuk suwir, kuah santan rempah Benteng, serundeng manis, tauge, daun bawang, emping melinjo.',
                'level_pedas' => 1,
                'rating'      => 4.8,
                'is_favorite' => 0,
                'gambar'      => 'laksa-daging-sapi.jpg',
                'status'      => 'tersedia',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nama'        => 'Laksa Benteng Telur Rebus & Tahu Bacem',
                'slug'        => 'laksa-benteng-telur-rebus-tahu-bacem',
                'kategori'    => 'Laksa Klasik',
                'harga'       => 22000,
                'deskripsi'   => 'Pilihan bersahabat kaya protein dengan potongan telur rebus gurih serta tahu bacem legit yang empuk, disiram kuah laksa kuning khas Tangerang.',
                'komposisi'   => 'Bihun beras, 1 butir telur ayam rebus, 2 potong tahu bacem gurih manis, kuah kuning santan, taburan serundeng, emping, seledri.',
                'level_pedas' => 1,
                'rating'      => 4.6,
                'is_favorite' => 0,
                'gambar'      => 'laksa-telur-tahu.jpg',
                'status'      => 'tersedia',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nama'        => 'Laksa Benteng Pedas Nampol Cabai Rawit',
                'slug'        => 'laksa-benteng-pedas-nampol-cabai-rawit',
                'kategori'    => 'Laksa Spesial',
                'harga'       => 28000,
                'deskripsi'   => 'Sensasi membakar bagi pecinta masakan pedas: laksa berkuah kental pedas menggelora dengan ulekan cabai rawit merah petik segar dan rempah jahe lengkuas hangat.',
                'komposisi'   => 'Bihun beras, ayam suwir pedas, kuah santan cabai rawit merah level 3, serundeng pedas, emping melinjo, daun jeruk purut, daun kesum.',
                'level_pedas' => 3,
                'rating'      => 4.8,
                'is_favorite' => 0,
                'gambar'      => 'laksa-pedas-nampol.jpg',
                'status'      => 'tersedia',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nama'        => 'Laksa Benteng Sultan Carlendra Grand Signature',
                'slug'        => 'laksa-benteng-sultan-carlendra-grand-signature',
                'kategori'    => 'Laksa Komplit',
                'harga'       => 55000,
                'deskripsi'   => 'Puncak kenikmatan kuliner warisan Tangerang: porsi raja berlimpah dengan ayam bakar kampung, udang windu jumbo, telur puyuh, ati ampela, dan serundeng emas.',
                'komposisi'   => 'Bihun beras ganda, paha ayam kampung bakar, 2 ekor udang windu jumbo, sate telur puyuh, ati ampela, kuah santan sari kaldu ganda, emping premium.',
                'level_pedas' => 2,
                'rating'      => 5.0,
                'is_favorite' => 1,
                'gambar'      => 'laksa-sultan-carlendra.jpg',
                'status'      => 'tersedia',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nama'        => 'Es Doger Benteng Kelapa Muda',
                'slug'        => 'es-doger-benteng-kelapa-muda',
                'kategori'    => 'Minuman Tradisional',
                'harga'       => 15000,
                'deskripsi'   => 'Minuman penutup legendaris penyejuk dahaga dengan serutan es santan merah muda, kelapa muda keruk, ketan hitam manis, pacar cina kenyal, dan sirup kental manis.',
                'komposisi'   => 'Es santan serut rasa cocopandan, daging kelapa muda, tape ketan hitam, tape singkong, pacar cina, roti tawar potong, susu kental manis.',
                'level_pedas' => 0,
                'rating'      => 4.9,
                'is_favorite' => 1,
                'gambar'      => 'es-doger-benteng.jpg',
                'status'      => 'tersedia',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'nama'        => 'Es Cincau Hitam Gula Aren Banten',
                'slug'        => 'es-cincau-hitam-gula-aren-banten',
                'kategori'    => 'Minuman Tradisional',
                'harga'       => 12000,
                'deskripsi'   => 'Minuman segar pelepas dahaga dari cincau hitam alami kenyal, dipadukan sirup gula aren murni khas Banten Selatan yang wangi dan santan gurih lembut.',
                'komposisi'   => 'Cincau hitam alami dadu, sirup kental gula aren asli Banten, santan kelapa perasan pertama, es batu kristal, daun pandan wangi.',
                'level_pedas' => 0,
                'rating'      => 4.7,
                'is_favorite' => 0,
                'gambar'      => 'es-cincau-aren.jpg',
                'status'      => 'tersedia',
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('menus')->truncate();
        $this->db->table('menus')->insertBatch($menus);
    }
}
